// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BW3nCmkWxHWKAVMgdQuZDnhbMOhUl2U',
    appId: '1:924802403362:web:0d9bb83acb5612df870e7b',
    messagingSenderId: '924802403362',
    projectId: 'testapp-57685',
    authDomain: 'testapp-57685.firebaseapp.com',
    storageBucket: 'testapp-57685.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmhBtJo6VyXr48m1Zg0sjAF90CMZkUiU',
    appId: '1:924802403362:android:f3cfe74738df63ea870e7b',
    messagingSenderId: '924802403362',
    projectId: 'testapp-57685',
    storageBucket: 'testapp-57685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDrXXxpDZ7_B4YS1VAAsB-oNfQDd2kSQ',
    appId: '1:924802403362:ios:a952d7cb076590cd870e7b',
    messagingSenderId: '924802403362',
    projectId: 'testapp-57685',
    storageBucket: 'testapp-57685.appspot.com',
    iosBundleId: 'com.example.krainet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDrXXxpDZ7_B4YS1VAAsB-oNfQDd2kSQ',
    appId: '1:924802403362:ios:6ad13e49b3ab9259870e7b',
    messagingSenderId: '924802403362',
    projectId: 'testapp-57685',
    storageBucket: 'testapp-57685.appspot.com',
    iosBundleId: 'com.example.krainet.RunnerTests',
  );
}
